[package]
name = "play-sqlx"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
futures = "0.3.30"
serde_json = "1.0.113"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-async-std"] }
